import React, { useState, useEffect } from 'react';
import { useInventory } from '../context/InventoryContext';
import { Plus, Trash2, Save, Info, X, Search } from 'lucide-react';

const PRODUCTS = [
    'Cafe Mocha',
    'Mango Peach Pie Crust',
    'Milky Chocolate',
    'Suman at Mangga',
    'Vanilla Langka'
];

const BATCH_NUMBERS = Array.from({ length: 14 }, (_, i) => i + 1);
const SHELF_LIFE_OPTIONS = [3, 4, 5, 6];

const StockIn = () => {
    const { inventory, addStock, history, addHistory } = useInventory();

    // Header Data
    const [headerData, setHeaderData] = useState({
        product: '',
        batchNumber: '',
        shelfLife: '',
        productionDate: '',
        churnedBy: '',
        pasteurizedBy: '',
        remarks: ''
    });

    // Rows Data
    const [rows, setRows] = useState([
        { id: Date.now(), sku: '', uom: '', quantity: '' }
    ]);

    const [availableSkus, setAvailableSkus] = useState([]);
    const [bestBeforeDate, setBestBeforeDate] = useState('AUTOCALCULATE');
    const [selectedEntry, setSelectedEntry] = useState(null);
    const [historySearchTerm, setHistorySearchTerm] = useState('');

    // Filter SKUs when Product changes
    useEffect(() => {
        if (headerData.product) {
            const filtered = inventory.filter(item =>
                item.description.includes(headerData.product)
            );
            setAvailableSkus(filtered);
            setRows(prev => prev.map(row => ({ ...row, sku: '' })));
        } else {
            setAvailableSkus([]);
        }
    }, [headerData.product, inventory]);

    // Calculate Best Before Date
    useEffect(() => {
        if (headerData.productionDate && headerData.shelfLife) {
            const date = new Date(headerData.productionDate);
            date.setMonth(date.getMonth() + parseInt(headerData.shelfLife));
            setBestBeforeDate(date.toLocaleDateString('en-US', {
                year: 'numeric', month: 'long', day: 'numeric'
            }));
        } else {
            setBestBeforeDate('AUTOCALCULATE');
        }
    }, [headerData.productionDate, headerData.shelfLife]);

    const handleHeaderChange = (e) => {
        const { name, value } = e.target;
        setHeaderData(prev => ({ ...prev, [name]: value }));
    };

    const handleRowChange = (id, field, value) => {
        setRows(prev => prev.map(row =>
            row.id === id ? { ...row, [field]: value } : row
        ));
    };

    const addRow = () => {
        setRows(prev => [...prev, { id: Date.now(), sku: '', uom: '', quantity: '' }]);
    };

    const removeRow = (id) => {
        if (rows.length > 1) {
            setRows(prev => prev.filter(row => row.id !== id));
        }
    };

    const getLotNumber = (sku) => {
        if (headerData.productionDate && headerData.batchNumber && sku) {
            const date = new Date(headerData.productionDate);
            const mm = String(date.getMonth() + 1).padStart(2, '0');
            const dd = String(date.getDate()).padStart(2, '0');
            const yy = String(date.getFullYear()).slice(-2);
            const dateStr = `${mm}${dd}${yy}`;
            const batchStr = String(headerData.batchNumber).padStart(2, '0');
            const skuPrefix = sku.split('-')[0];
            return `${dateStr}B${batchStr}${skuPrefix}`;
        }
        return 'AUTOGENERATED';
    };

    const handleSubmit = (e) => {
        e.preventDefault();

        if (!headerData.product || !headerData.batchNumber || !headerData.productionDate) {
            alert('Please fill in all header details.');
            return;
        }

        const validRows = rows.filter(r => r.sku && r.quantity);
        if (validRows.length === 0) {
            alert('Please add at least one valid item row.');
            return;
        }

        // Process each row
        validRows.forEach(row => {
            addStock(row.sku, row.quantity);

            // Add to history
            const skuItem = inventory.find(i => i.sku === row.sku);
            const historyEntry = {
                id: Date.now() + Math.random(), // Unique ID
                date: new Date().toLocaleDateString(),
                sku: row.sku,
                description: skuItem ? skuItem.description : 'Unknown',
                quantity: row.quantity,
                lotNumber: getLotNumber(row.sku),
                // Full details for "More Info"
                details: {
                    ...headerData,
                    uom: row.uom,
                    bestBefore: bestBeforeDate
                }
            };
            addHistory(historyEntry);
        });

        alert(`Successfully added stock for ${validRows.length} items!`);

        // Reset
        setHeaderData({
            product: '',
            batchNumber: '',
            shelfLife: '',
            productionDate: '',
            churnedBy: '',
            pasteurizedBy: '',
            remarks: ''
        });
        setRows([{ id: Date.now(), sku: '', uom: '', quantity: '' }]);
    };

    // Filter history
    const filteredHistory = history.filter(entry =>
        entry.sku.toLowerCase().includes(historySearchTerm.toLowerCase()) ||
        entry.description.toLowerCase().includes(historySearchTerm.toLowerCase()) ||
        entry.lotNumber.toLowerCase().includes(historySearchTerm.toLowerCase())
    );

    return (
        <div className="fade-in">
            <div className="header-section" style={{ marginBottom: '1rem' }}>
                <h2 className="page-title" style={{ fontSize: '1.5rem' }}>New Stock Entry</h2>
                <p className="page-subtitle" style={{ fontSize: '0.875rem' }}>Create a new production batch entry</p>
            </div>

            <form onSubmit={handleSubmit} className="stock-in-form">
                {/* Combined Header Info */}
                <div className="form-card" style={{ padding: '1rem', marginBottom: '1.5rem' }}>
                    <h3 className="card-heading" style={{ fontSize: '1rem', marginBottom: '0.75rem' }}>Batch Information</h3>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
                        {/* Row 1 */}
                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Product Line</label>
                            <select name="product" value={headerData.product} onChange={handleHeaderChange} required className="premium-input" style={{ padding: '0.4rem', fontSize: '0.875rem' }}>
                                <option value="">Select Product</option>
                                {PRODUCTS.map(p => <option key={p} value={p}>{p}</option>)}
                            </select>
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Batch No.</label>
                            <select name="batchNumber" value={headerData.batchNumber} onChange={handleHeaderChange} required className="premium-input" style={{ padding: '0.4rem', fontSize: '0.875rem' }}>
                                <option value="">Select Batch</option>
                                {BATCH_NUMBERS.map(n => <option key={n} value={n}>{n}</option>)}
                            </select>
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Production Date</label>
                            <input
                                type="date"
                                name="productionDate"
                                value={headerData.productionDate}
                                onChange={handleHeaderChange}
                                required
                                className="premium-input"
                                style={{ padding: '0.4rem', fontSize: '0.875rem' }}
                            />
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Shelf Life</label>
                            <select name="shelfLife" value={headerData.shelfLife} onChange={handleHeaderChange} required className="premium-input" style={{ padding: '0.4rem', fontSize: '0.875rem' }}>
                                <option value="">Select Duration</option>
                                {SHELF_LIFE_OPTIONS.map(m => <option key={m} value={m}>{m} months</option>)}
                            </select>
                        </div>

                        {/* Row 2 */}
                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Best Before</label>
                            <div className="read-only-field premium-input" style={{ padding: '0.4rem', fontSize: '0.875rem', backgroundColor: '#f9fafb' }}>{bestBeforeDate}</div>
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Churned By</label>
                            <input
                                type="text"
                                name="churnedBy"
                                value={headerData.churnedBy}
                                onChange={handleHeaderChange}
                                placeholder="Name"
                                className="premium-input"
                                style={{ padding: '0.4rem', fontSize: '0.875rem' }}
                            />
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Pasteurized By</label>
                            <input
                                type="text"
                                name="pasteurizedBy"
                                value={headerData.pasteurizedBy}
                                onChange={handleHeaderChange}
                                placeholder="Name"
                                className="premium-input"
                                style={{ padding: '0.4rem', fontSize: '0.875rem' }}
                            />
                        </div>

                        <div className="form-group" style={{ marginBottom: 0 }}>
                            <label style={{ fontSize: '0.75rem' }}>Remarks</label>
                            <input
                                type="text"
                                name="remarks"
                                value={headerData.remarks}
                                onChange={handleHeaderChange}
                                placeholder="Notes..."
                                className="premium-input"
                                style={{ padding: '0.4rem', fontSize: '0.875rem' }}
                            />
                        </div>
                    </div>
                </div>

                {/* Split View: Items & History */}
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '1.5rem', alignItems: 'flex-start' }}>

                    {/* LEFT: Production Items */}
                    <div style={{ flex: '1 1 500px', minWidth: '300px' }}>
                        <div className="form-card" style={{ padding: '1rem', marginBottom: '1rem' }}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
                                <h3 className="card-heading" style={{ fontSize: '1rem', marginBottom: 0 }}>Production Items</h3>
                                <button type="button" onClick={addRow} className="text-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.875rem', fontWeight: '500', background: 'none', border: 'none', cursor: 'pointer' }}>
                                    <Plus size={16} /> Add Item
                                </button>
                            </div>

                            <div className="table-container" style={{ overflow: 'visible' }}>
                                <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: '0 0.5rem' }}>
                                    <thead>
                                        <tr>
                                            <th style={{ textAlign: 'left', fontSize: '0.75rem', color: 'var(--text-secondary)', padding: '0 0.5rem' }}>SKU</th>
                                            <th style={{ textAlign: 'left', fontSize: '0.75rem', color: 'var(--text-secondary)', padding: '0 0.5rem', width: '80px' }}>UOM</th>
                                            <th style={{ textAlign: 'left', fontSize: '0.75rem', color: 'var(--text-secondary)', padding: '0 0.5rem', width: '80px' }}>Qty</th>
                                            <th style={{ textAlign: 'left', fontSize: '0.75rem', color: 'var(--text-secondary)', padding: '0 0.5rem', width: '140px' }}>Lot No.</th>
                                            <th style={{ width: '30px' }}></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {rows.map((row) => (
                                            <tr key={row.id}>
                                                <td style={{ padding: '0 0.5rem' }}>
                                                    <select
                                                        value={row.sku}
                                                        onChange={(e) => handleRowChange(row.id, 'sku', e.target.value)}
                                                        required
                                                        disabled={!headerData.product}
                                                        className="premium-input"
                                                        style={{ width: '100%', padding: '0.4rem', fontSize: '0.875rem' }}
                                                    >
                                                        <option value="">Select SKU</option>
                                                        {availableSkus.map(item => (
                                                            <option key={item.sku} value={item.sku}>
                                                                {item.sku.split('-')[0]} - {item.description}
                                                            </option>
                                                        ))}
                                                    </select>
                                                </td>
                                                <td style={{ padding: '0 0.5rem' }}>
                                                    <select
                                                        value={row.uom}
                                                        onChange={(e) => handleRowChange(row.id, 'uom', e.target.value)}
                                                        required
                                                        className="premium-input"
                                                        style={{ width: '100%', padding: '0.4rem', fontSize: '0.875rem' }}
                                                    >
                                                        <option value="">Select</option>
                                                        <option value="PCS">PCS</option>
                                                        <option value="PACK">PACK</option>
                                                    </select>
                                                </td>
                                                <td style={{ padding: '0 0.5rem' }}>
                                                    <input
                                                        type="number"
                                                        value={row.quantity}
                                                        onChange={(e) => handleRowChange(row.id, 'quantity', e.target.value)}
                                                        placeholder="0"
                                                        required
                                                        className="premium-input"
                                                        style={{ width: '100%', padding: '0.4rem', fontSize: '0.875rem' }}
                                                    />
                                                </td>
                                                <td style={{ padding: '0 0.5rem' }}>
                                                    <div className="read-only-field premium-input" style={{ padding: '0.4rem', fontSize: '0.75rem', backgroundColor: '#f9fafb', height: '38px', display: 'flex', alignItems: 'center', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                                                        {getLotNumber(row.sku)}
                                                    </div>
                                                </td>
                                                <td style={{ padding: '0 0.5rem', textAlign: 'center' }}>
                                                    {rows.length > 1 && (
                                                        <button
                                                            type="button"
                                                            onClick={() => removeRow(row.id)}
                                                            className="icon-btn delete-btn"
                                                            title="Remove Item"
                                                            style={{ padding: '0.25rem' }}
                                                        >
                                                            <Trash2 size={16} />
                                                        </button>
                                                    )}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div className="action-bar" style={{ marginTop: '0' }}>
                            <button type="submit" className="submit-btn" style={{ width: '100%' }}>
                                <Save size={18} />
                                Save Stock Entry
                            </button>
                        </div>
                    </div>

                    {/* RIGHT: History */}
                    <div style={{ flex: '1 1 500px', minWidth: '300px' }}>
                        <div className="form-card" style={{ padding: '0', overflow: 'hidden', height: '100%', display: 'flex', flexDirection: 'column' }}>
                            <div style={{ padding: '1rem', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff' }}>
                                <h3 className="card-heading" style={{ fontSize: '1rem', marginBottom: 0, border: 'none', padding: 0 }}>History</h3>
                                <div style={{ position: 'relative' }}>
                                    <Search size={14} style={{ position: 'absolute', left: '8px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-secondary)' }} />
                                    <input
                                        type="text"
                                        placeholder="Search history..."
                                        value={historySearchTerm}
                                        onChange={(e) => setHistorySearchTerm(e.target.value)}
                                        style={{
                                            padding: '0.3rem 0.6rem 0.3rem 2rem',
                                            fontSize: '0.8rem',
                                            border: '1px solid var(--border-color)',
                                            borderRadius: 'var(--radius-md)',
                                            outline: 'none',
                                            width: '160px'
                                        }}
                                    />
                                </div>
                            </div>

                            <div className="table-container" style={{ maxHeight: '400px', overflowY: 'auto' }}>
                                <table className="inventory-table" style={{ fontSize: '0.8rem' }}>
                                    <thead style={{ position: 'sticky', top: 0, zIndex: 1, backgroundColor: 'var(--gray-50)' }}>
                                        <tr>
                                            <th style={{ padding: '0.5rem 0.75rem' }}>Date</th>
                                            <th style={{ padding: '0.5rem 0.75rem' }}>SKU</th>
                                            <th style={{ padding: '0.5rem 0.75rem' }}>Qty</th>
                                            <th style={{ padding: '0.5rem 0.75rem' }}>Lot No.</th>
                                            <th style={{ padding: '0.5rem 0.75rem' }}></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {filteredHistory.length === 0 ? (
                                            <tr>
                                                <td colSpan="5" className="empty-state" style={{ padding: '1.5rem', textAlign: 'center' }}>
                                                    {historySearchTerm ? 'No matching records.' : 'No history yet.'}
                                                </td>
                                            </tr>
                                        ) : (
                                            filteredHistory.map(entry => (
                                                <tr key={entry.id}>
                                                    <td style={{ padding: '0.5rem 0.75rem' }}>{entry.date}</td>
                                                    <td className="font-medium" style={{ padding: '0.5rem 0.75rem' }}>{entry.sku}</td>
                                                    <td style={{ padding: '0.5rem 0.75rem' }}>{entry.quantity}</td>
                                                    <td className="font-mono text-xs" style={{ padding: '0.5rem 0.75rem' }}>{entry.lotNumber}</td>
                                                    <td style={{ padding: '0.5rem 0.75rem' }}>
                                                        <button
                                                            type="button"
                                                            className="icon-btn text-primary"
                                                            onClick={() => setSelectedEntry(entry)}
                                                            title="More Info"
                                                            style={{ padding: '0.25rem' }}
                                                        >
                                                            <Info size={16} />
                                                        </button>
                                                    </td>
                                                </tr>
                                            ))
                                        )}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </form>

            {/* Details Modal */}
            {selectedEntry && (
                <div className="modal-overlay" onClick={() => setSelectedEntry(null)}>
                    <div className="modal-content" onClick={e => e.stopPropagation()}>
                        <div className="modal-header">
                            <h2 className="modal-title">Transaction Details</h2>
                            <button className="close-btn" onClick={() => setSelectedEntry(null)}>
                                <X size={24} />
                            </button>
                        </div>

                        <div className="modal-body">
                            {/* Batch Details */}
                            <div className="form-card">
                                <h3 className="card-heading">Batch Details</h3>
                                <div className="form-grid">
                                    <div className="form-group">
                                        <label>Product Line</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.product}</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Batch No.</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.batchNumber}</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Shelf Life</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.shelfLife} months</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Production Date</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.productionDate}</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Best Before</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.bestBefore}</div>
                                    </div>
                                </div>
                            </div>

                            {/* Production Items (Specific Item) */}
                            <div className="form-card">
                                <h3 className="card-heading">Production Items</h3>
                                <div className="rows-container">
                                    <div className="item-row">
                                        <div className="form-group sku-group">
                                            <label>SKU</label>
                                            <div className="read-only-field premium-input">{selectedEntry.sku} - {selectedEntry.description}</div>
                                        </div>

                                        <div className="form-group uom-group">
                                            <label>UOM</label>
                                            <div className="read-only-field premium-input">{selectedEntry.details.uom}</div>
                                        </div>

                                        <div className="form-group qty-group">
                                            <label>Quantity</label>
                                            <div className="read-only-field premium-input">{selectedEntry.quantity}</div>
                                        </div>

                                        <div className="form-group lot-group">
                                            <label>Lot Number</label>
                                            <div className="read-only-field premium-input">{selectedEntry.lotNumber}</div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Additional Details */}
                            <div className="form-card">
                                <h3 className="card-heading">Additional Details</h3>
                                <div className="form-grid three-cols">
                                    <div className="form-group">
                                        <label>Churned By</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.churnedBy || '-'}</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Pasteurized By</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.pasteurizedBy || '-'}</div>
                                    </div>

                                    <div className="form-group">
                                        <label>Remarks</label>
                                        <div className="read-only-field premium-input">{selectedEntry.details.remarks || '-'}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default StockIn;
